### ISSUE TITLE
linearEqSolver won't build with GHC 9.8.4

### ISSUE THREAD

**Issue by tewk** [LeventErkok/linearEqSolver#5]
```
[1 of 1] Compiling Math.LinearEquationSolver ( Math/LinearEquationSolver.hs, dist/build/Math/LinearEquationSolver.o, dist/build/Math/LinearEquationSolver.dyn_o )

Math/LinearEquationSolver.hs:149:26: error: [GHC-39999]
    • Could not deduce ‘Num (SBV a)’ arising from a use of ‘sum’
      from the context: (Ord a, Num a, SymVal a)
        bound by the type signature for:
                   buildConstraints :: forall a.
                                       (Ord a, Num a, SymVal a) =>
                                       String -> [[a]] -> [a] -> Symbolic SBool
        at Math/LinearEquationSolver.hs:143:1-88
    • In the first argument of ‘(.==)’, namely
        ‘sum (zipWith (*) xs row)’
      In the expression: sum (zipWith (*) xs row) .== r
      In an equation for ‘rowEq’:
          rowEq row r = sum (zipWith (*) xs row) .== r
    |
149 |        let rowEq row r = sum (zipWith (*) xs row) .== r
    |                          ^^^
Error: [Cabal-7125]
```

**Comment by LeventErkok** [comment]
@tewk Thanks for the report. Version 2.4 is now on Hackage, which should compile cleanly. Let me know if you find otherwise.
